version: "3.8"
services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    environment:
      MP_MAX_MESSAGES: 100000
      MP_WEBROOT: /
      MP_UI_AUTH: ""   # set "user:pass" to protect UI
    restart: unless-stopped